### ISSUE TITLE
Communitheme Snap Icon Set Not Taking Advantage Of New Upstream Icons

### ISSUE THREAD

**Issue by duke7553** [ubuntu/communitheme-icon-theme#2]
Many new icons have been added to the official Suru repository, but are still missing from the snap. This looks rather incomplete. Are there any roadblocks to adding these?

Thanks,
Luke

**Comment by Feichtmeier** [comment]
Yes, we will pull all changes sam adds to his repo!

**Comment by galgalesh** [comment]
Thanks for letting me know. For some reason, I forgot to merge the PR to import te latest changes. I re-synced with sam's repo, the snap should be available in the edge channel shortly and the updates will go to stable with the next communitheme stable release by @clobrano.

Reopen this issue and let me know if there are any issues.
